apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260507-145109-coijb0ckr0dp-service
spec:
  selector:
    app: enterprise-system-20260507-145109-coijb0ckr0dp
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
